"""Asynchronous client for the Open-Meteo API."""

from .exceptions import OpenMeteoConnectionError, OpenMeteoError
from .models import (
    AirQuality,
    AirQualityDomain,
    AirQualityParameters,
    CellSelection,
    CurrentAirQuality,
    CurrentAirQualityUnits,
    CurrentForecast,
    CurrentForecastUnits,
    DailyForecast,
    DailyForecastUnits,
    DailyParameters,
    Elevation,
    Forecast,
    Geocoding,
    GeocodingResult,
    HourlyAirQuality,
    HourlyAirQualityUnits,
    HourlyForecast,
    HourlyForecastUnits,
    HourlyParameters,
    Minutely15Forecast,
    Minutely15ForecastUnits,
    PrecipitationUnit,
    TemperatureUnit,
    TemporalResolution,
    TimeFormat,
    WindSpeedUnit,
)
from .open_meteo import OpenMeteo

__all__ = [
    "AirQuality",
    "AirQualityDomain",
    "AirQualityParameters",
    "CellSelection",
    "CurrentAirQuality",
    "CurrentAirQualityUnits",
    "CurrentForecast",
    "CurrentForecastUnits",
    "DailyForecast",
    "DailyForecastUnits",
    "DailyParameters",
    "Elevation",
    "Forecast",
    "Geocoding",
    "GeocodingResult",
    "HourlyAirQuality",
    "HourlyAirQualityUnits",
    "HourlyForecast",
    "HourlyForecastUnits",
    "HourlyParameters",
    "Minutely15Forecast",
    "Minutely15ForecastUnits",
    "OpenMeteo",
    "OpenMeteoConnectionError",
    "OpenMeteoError",
    "PrecipitationUnit",
    "TemperatureUnit",
    "TemporalResolution",
    "TimeFormat",
    "WindSpeedUnit",
]
