"""Asynchronous client for the Open-Meteo API."""

from .exceptions import OpenMeteoConnectionError, OpenMeteoError
from .models import (
    AirQuality,
    AirQualityParameters,
    CurrentWeather,
    CurrentAirQuality,
    CurrentAirQualityUnits,
    DailyForecast,
    DailyForecastUnits,
    DailyParameters,
    Forecast,
    Geocoding,
    GeocodingResult,
    HourlyForecast,
    HourlyForecastUnits,
    HourlyParameters,
    HourlyAirQuality,
    HourlyAirQualityUnits,
    PrecipitationUnit,
    TemperatureUnit,
    TimeFormat,
    WindSpeedUnit,
)
from .open_meteo import OpenMeteo

__all__ = [
    "AirQuality",
    "AirQualityParameters",
    "CurrentWeather",
    "CurrentAirQuality",
    "CurrentAirQualityUnits",
    "DailyForecast",
    "DailyForecastUnits",
    "DailyParameters",
    "Forecast",
    "Geocoding",
    "GeocodingResult",
    "HourlyForecast",
    "HourlyForecastUnits",
    "HourlyParameters",
    "HourlyAirQuality",
    "HourlyAirQualityUnits",
    "OpenMeteo",
    "OpenMeteoConnectionError",
    "OpenMeteoError",
    "PrecipitationUnit",
    "TemperatureUnit",
    "TimeFormat",
    "WindSpeedUnit",
]
