"""Models for the Open-Meteo marine weather API."""

# pylint: disable=too-many-instance-attributes

from dataclasses import dataclass, field
from datetime import date, datetime
from enum import StrEnum
from typing import Any

from mashumaro import field_options
from mashumaro.mixins.orjson import DataClassORJSONMixin

from ._split import _drop_suffixed, _split_members
from .common import TimeFormat


class LengthUnit(StrEnum):
    """Enum to represent the length units available, for wave heights."""

    METRIC = "metric"
    IMPERIAL = "imperial"


class MarineParameters(StrEnum):
    """Enum to represent the marine parameters available.

    These can be requested as current conditions, 15-minutely, and hourly.
    Which variables have data depends on the location and the marine model.
    """

    # Significant height, mean direction, and mean period of all waves
    # combined: wind waves and swell
    WAVE_HEIGHT = "wave_height"
    WAVE_DIRECTION = "wave_direction"
    WAVE_PERIOD = "wave_period"

    # Period of the most energetic waves
    WAVE_PEAK_PERIOD = "wave_peak_period"

    # Waves generated by the local wind
    WIND_WAVE_HEIGHT = "wind_wave_height"
    WIND_WAVE_DIRECTION = "wind_wave_direction"
    WIND_WAVE_PERIOD = "wind_wave_period"
    WIND_WAVE_PEAK_PERIOD = "wind_wave_peak_period"

    # Swell: waves generated by distant weather systems, that travelled to the
    # location
    SWELL_WAVE_HEIGHT = "swell_wave_height"
    SWELL_WAVE_DIRECTION = "swell_wave_direction"
    SWELL_WAVE_PERIOD = "swell_wave_period"
    SWELL_WAVE_PEAK_PERIOD = "swell_wave_peak_period"

    # Second and third swell system, for locations reached by swell from
    # multiple directions
    SECONDARY_SWELL_WAVE_HEIGHT = "secondary_swell_wave_height"
    SECONDARY_SWELL_WAVE_DIRECTION = "secondary_swell_wave_direction"
    SECONDARY_SWELL_WAVE_PERIOD = "secondary_swell_wave_period"
    TERTIARY_SWELL_WAVE_HEIGHT = "tertiary_swell_wave_height"
    TERTIARY_SWELL_WAVE_DIRECTION = "tertiary_swell_wave_direction"
    TERTIARY_SWELL_WAVE_PERIOD = "tertiary_swell_wave_period"

    # Sea level height including tides, above the global mean sea level
    SEA_LEVEL_HEIGHT_MSL = "sea_level_height_msl"

    # Sea level change caused by air pressure, the inverted barometer effect
    INVERT_BAROMETER_HEIGHT = "invert_barometer_height"

    # Sea surface temperature
    SEA_SURFACE_TEMPERATURE = "sea_surface_temperature"

    # Ocean current velocity and direction
    OCEAN_CURRENT_VELOCITY = "ocean_current_velocity"
    OCEAN_CURRENT_DIRECTION = "ocean_current_direction"


class MarineDailyParameters(StrEnum):
    """Enum to represent the daily marine parameters available."""

    # Maximum significant height, dominant direction, and maximum period of all
    # waves combined
    WAVE_HEIGHT_MAX = "wave_height_max"
    WAVE_DIRECTION_DOMINANT = "wave_direction_dominant"
    WAVE_PERIOD_MAX = "wave_period_max"

    # The same for waves generated by the local wind
    WIND_WAVE_HEIGHT_MAX = "wind_wave_height_max"
    WIND_WAVE_DIRECTION_DOMINANT = "wind_wave_direction_dominant"
    WIND_WAVE_PERIOD_MAX = "wind_wave_period_max"
    WIND_WAVE_PEAK_PERIOD_MAX = "wind_wave_peak_period_max"

    # The same for swell
    SWELL_WAVE_HEIGHT_MAX = "swell_wave_height_max"
    SWELL_WAVE_DIRECTION_DOMINANT = "swell_wave_direction_dominant"
    SWELL_WAVE_PERIOD_MAX = "swell_wave_period_max"
    SWELL_WAVE_PEAK_PERIOD_MAX = "swell_wave_peak_period_max"


@dataclass
class CurrentMarine(DataClassORJSONMixin):
    """Current marine conditions."""

    time: datetime
    interval: int
    wave_height: float | None = None
    wave_direction: int | None = None
    wave_period: float | None = None
    wave_peak_period: float | None = None
    wind_wave_height: float | None = None
    wind_wave_direction: int | None = None
    wind_wave_period: float | None = None
    wind_wave_peak_period: float | None = None
    swell_wave_height: float | None = None
    swell_wave_direction: int | None = None
    swell_wave_period: float | None = None
    swell_wave_peak_period: float | None = None
    secondary_swell_wave_height: float | None = None
    secondary_swell_wave_direction: int | None = None
    secondary_swell_wave_period: float | None = None
    tertiary_swell_wave_height: float | None = None
    tertiary_swell_wave_direction: int | None = None
    tertiary_swell_wave_period: float | None = None
    sea_level_height_msl: float | None = None
    invert_barometer_height: float | None = None
    sea_surface_temperature: float | None = None
    ocean_current_velocity: float | None = None
    ocean_current_direction: int | None = None


@dataclass
class CurrentMarineUnits(DataClassORJSONMixin):
    """Current marine conditions units."""

    time: TimeFormat | None = None
    interval: str | None = None
    wave_height: str | None = None
    wave_direction: str | None = None
    wave_period: str | None = None
    wave_peak_period: str | None = None
    wind_wave_height: str | None = None
    wind_wave_direction: str | None = None
    wind_wave_period: str | None = None
    wind_wave_peak_period: str | None = None
    swell_wave_height: str | None = None
    swell_wave_direction: str | None = None
    swell_wave_period: str | None = None
    swell_wave_peak_period: str | None = None
    secondary_swell_wave_height: str | None = None
    secondary_swell_wave_direction: str | None = None
    secondary_swell_wave_period: str | None = None
    tertiary_swell_wave_height: str | None = None
    tertiary_swell_wave_direction: str | None = None
    tertiary_swell_wave_period: str | None = None
    sea_level_height_msl: str | None = None
    invert_barometer_height: str | None = None
    sea_surface_temperature: str | None = None
    ocean_current_velocity: str | None = None
    ocean_current_direction: str | None = None


@dataclass
class HourlyMarine(DataClassORJSONMixin):
    """Hourly marine data."""

    time: list[datetime]
    wave_height: list[float | None] | None = None
    wave_direction: list[int | None] | None = None
    wave_period: list[float | None] | None = None
    wave_peak_period: list[float | None] | None = None
    wind_wave_height: list[float | None] | None = None
    wind_wave_direction: list[int | None] | None = None
    wind_wave_period: list[float | None] | None = None
    wind_wave_peak_period: list[float | None] | None = None
    swell_wave_height: list[float | None] | None = None
    swell_wave_direction: list[int | None] | None = None
    swell_wave_period: list[float | None] | None = None
    swell_wave_peak_period: list[float | None] | None = None
    secondary_swell_wave_height: list[float | None] | None = None
    secondary_swell_wave_direction: list[int | None] | None = None
    secondary_swell_wave_period: list[float | None] | None = None
    tertiary_swell_wave_height: list[float | None] | None = None
    tertiary_swell_wave_direction: list[int | None] | None = None
    tertiary_swell_wave_period: list[float | None] | None = None
    sea_level_height_msl: list[float | None] | None = None
    invert_barometer_height: list[float | None] | None = None
    sea_surface_temperature: list[float | None] | None = None
    ocean_current_velocity: list[float | None] | None = None
    ocean_current_direction: list[int | None] | None = None

    # Only set for ensemble models, keyed by member number
    members: "dict[int, HourlyMarine] | None" = None

    @classmethod
    def __pre_deserialize__(cls, d: dict[Any, Any]) -> dict[Any, Any]:
        """Group the ensemble members by member number."""
        return _split_members(d)


@dataclass
class HourlyMarineUnits(DataClassORJSONMixin):
    """Hourly marine data units."""

    time: TimeFormat | None = None
    wave_height: str | None = None
    wave_direction: str | None = None
    wave_period: str | None = None
    wave_peak_period: str | None = None
    wind_wave_height: str | None = None
    wind_wave_direction: str | None = None
    wind_wave_period: str | None = None
    wind_wave_peak_period: str | None = None
    swell_wave_height: str | None = None
    swell_wave_direction: str | None = None
    swell_wave_period: str | None = None
    swell_wave_peak_period: str | None = None
    secondary_swell_wave_height: str | None = None
    secondary_swell_wave_direction: str | None = None
    secondary_swell_wave_period: str | None = None
    tertiary_swell_wave_height: str | None = None
    tertiary_swell_wave_direction: str | None = None
    tertiary_swell_wave_period: str | None = None
    sea_level_height_msl: str | None = None
    invert_barometer_height: str | None = None
    sea_surface_temperature: str | None = None
    ocean_current_velocity: str | None = None
    ocean_current_direction: str | None = None

    @classmethod
    def __pre_deserialize__(cls, d: dict[Any, Any]) -> dict[Any, Any]:
        """Drop the units of ensemble members."""
        return _drop_suffixed(d)


@dataclass
class Minutely15Marine(HourlyMarine):
    """15-minutely marine data."""


@dataclass
class Minutely15MarineUnits(HourlyMarineUnits):
    """15-minutely marine data units."""


@dataclass
class DailyMarine(DataClassORJSONMixin):
    """Daily marine data."""

    time: list[date]
    wave_height_max: list[float | None] | None = None
    wave_direction_dominant: list[int | None] | None = None
    wave_period_max: list[float | None] | None = None
    wind_wave_height_max: list[float | None] | None = None
    wind_wave_direction_dominant: list[int | None] | None = None
    wind_wave_period_max: list[float | None] | None = None
    wind_wave_peak_period_max: list[float | None] | None = None
    swell_wave_height_max: list[float | None] | None = None
    swell_wave_direction_dominant: list[int | None] | None = None
    swell_wave_period_max: list[float | None] | None = None
    swell_wave_peak_period_max: list[float | None] | None = None

    # Only set for ensemble models, keyed by member number
    members: "dict[int, DailyMarine] | None" = None

    @classmethod
    def __pre_deserialize__(cls, d: dict[Any, Any]) -> dict[Any, Any]:
        """Group the ensemble members by member number."""
        return _split_members(d)


@dataclass
class DailyMarineUnits(DataClassORJSONMixin):
    """Daily marine data units."""

    time: TimeFormat | None = None
    wave_height_max: str | None = None
    wave_direction_dominant: str | None = None
    wave_period_max: str | None = None
    wind_wave_height_max: str | None = None
    wind_wave_direction_dominant: str | None = None
    wind_wave_period_max: str | None = None
    wind_wave_peak_period_max: str | None = None
    swell_wave_height_max: str | None = None
    swell_wave_direction_dominant: str | None = None
    swell_wave_period_max: str | None = None
    swell_wave_peak_period_max: str | None = None

    @classmethod
    def __pre_deserialize__(cls, d: dict[Any, Any]) -> dict[Any, Any]:
        """Drop the units of ensemble members."""
        return _drop_suffixed(d)


@dataclass
class Marine(DataClassORJSONMixin):
    """Marine forecast."""

    elevation: float
    generation_time_ms: float = field(metadata=field_options(alias="generationtime_ms"))
    latitude: float
    longitude: float
    timezone: str
    timezone_abbreviation: str
    utc_offset_seconds: int
    current_units: CurrentMarineUnits | None = None
    current: CurrentMarine | None = None
    minutely_15_units: Minutely15MarineUnits | None = None
    minutely_15: Minutely15Marine | None = None
    hourly_units: HourlyMarineUnits | None = None
    hourly: HourlyMarine | None = None
    daily_units: DailyMarineUnits | None = None
    daily: DailyMarine | None = None

    # Only set when multiple models were requested, keyed by the model name
    models: "dict[str, Marine] | None" = None
